flags = [
    "-vulkan",
    "-malloc=system",
    "-novid",
    "-lv",
    "-nojoy",
    "-background $(shuf -i 1-5 -n 1)",
    "-cl_disablehtmlmotd 1",
    "+mat_queue_mode 2"
]

[env]
vblank_mode = "0"
MESA_VK_WSI_PRESENT_MODE = "immediate"
SDL_VIDEODRIVER = "wayland"
STEAM_COMPAT_RUNTIME_SDL2 = "1"

[gamescope]
width = 800
height = 600
scaler = "stretch"
fullscreen = true
flags = [
    "--force-grab-cursor",
    "--immediate-flips",
]

[dll-overrides]

